name: CI

on:
  push:
    branches: [main, develop, develop_tw]
  pull_request:
    branches: [main, develop, develop_tw]

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["^3.10"]
        poetry-version: ["1.4"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with black
        run: |
          poetry run black . --check
      - name: Run pytest with poetry
        run: |
          poetry run pytest